[package] # cmk update this
edition = "2021"
# if this changes, update .vscode/launch.json and .cargo/config.toml
name = "clock"
version = "0.1.1"

# The `[lib]` section defines the library part of this binary project.
# It allows `src/lib.rs` to act as the central hub for shared code,
# which can be reused across binaries or tests.
[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
defmt = "0.3.8"
defmt-rtt = "0.4.1"
panic-probe = { version = "0.3", features = ["print-defmt"] }
cortex-m-rt = "0.7.5"
cortex-m = "0.7.7"
embassy-executor = { version = "0.6.3", features = [
    "arch-cortex-m",
    "executor-thread",
    "defmt",
    "integrated-timers",
] }
embassy-sync = { version = "0.6.1" }
embassy-rp = { version = "0.2.0", features = [
    "defmt",
    "time-driver",
    "critical-section-impl",
] }
embassy-futures = { version = "0.1.1" }
embassy-time = { version = "0.3.2", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }
heapless = "0.8"
derive_more = { version = "1.0.0", default-features = false, features = [
    "debug",
    "display",
    "error",
    "from",
] }

[build-dependencies]
chrono = "0.4.19"
